### ISSUE TITLE
Weapon balance issues

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/raclassic#153]
- Damage of 90mm and 105mm should be 30 (as in original), not 40.
40 makes the Medium Tank too good and robs Light Tank of its dps advantage,
and also gives Heavy Tank higher anti-tank/-building dps than Mammoth (!).
Pretty sure the BurstDelay of 105mm should be at least 5 as well.

- although unrealistic, machine guns in the original could shoot over walls, blocking them puts MG units/defense at an even bigger disadvantage vs tanks. Just sayin'.

- MammothTusk should be (much) slower, something around speed 300 (or less). It's somewhat OP vs infantry even with that, so at least it shouldn't be as good vs (fast) aircraft.

There might be more, but those were the most noticable to me.

**Comment by MustaphaTR** [comment]
> although unrealistic, machine guns in the original could shoot over walls, blocking them puts MG units/defense at an even bigger disadvantage vs tanks. Just sayin'.

This was an intented change, tho we may reconsider it.

**Comment by MustaphaTR** [comment]
> MammothTusk should be (much) slower, something around speed 300 (or less). It's somewhat OP vs infantry even with that, so at least it shouldn't be as good vs (fast) aircraft.

It seems to have same projectile speed as Maverick and Hellfire, 30. We used 15x for everything so current 450 seems correct. It is still way slower than other missiles with 750/50.
