### ISSUE TITLE
Shift-click on structures in menu

### ISSUE THREAD

**Issue by nr1995** [OpenRA/raclassic#186]
When you shift-click on a structure in the build menu,
it queues up 5 of the same structure to be built in a row.
Although this could be an OpenRA problem...

**Comment by MustaphaTR** [comment]
That's intended, it is what Shift+Click does in all queues, no exception. It is unlikely that you would need to use it for any building, maybe except defences or power plants, but no need to create exceptions.
If you do it by mistake, shift+rightclick can cancel 5, and ctrl+rightclick can cancel all too.

**Comment by nr1995** [comment]
> That's intended, it is what Shift+Click on OpenRA does in all queues, no exception. It is unlikely that you would need to use it for any building, maybe except defences or power plants, but no need to create exceptions.
> If you do it by mistake, shift+rightclick can cancel 5, and ctrl+rightclick can cancel all too.

**_Five_** though?  I mean, two... maybe three...  But **_five_** ?
I've never seen anything like that in 25 years.
Well, then, could we get the option to edit which keys do the [Ctrl] and [Shift] functions?
They're the only ones not listed in the Hotkeys sub-menu.

**Comment by MustaphaTR** [comment]
It is meant for units mostly as i said, not buildings. Especially handly for infantry. It is not possible for me to change the number for a specific queue.
It is also not possible to make functions of Ctrl and Shift right now. PChote should have a better explanition on why, i'm not 100% sure.
If you really wanna complain about this, please create an issue in https://github.com/OpenRA/OpenRA , as it is not possible to change either in the mod level.
